# Generated by Django 2.2.1 on 2019-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpn',
            options={'ordering': ('-score',)},
        ),
        migrations.AlterField(
            model_name='vpn',
            name='ping',
            field=models.CharField(max_length=100),
        ),
    ]
